image: node:6.2

cache:
    paths:
        - node_modules/

before_script:
    - npm install --silent
    - node_modules/.bin/typings install

run_tests:
    script:
        - npm run lint
        - npm test
    tags:
        - node
